# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(407, 407)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 10, 211, 101))
        self.pushButton.setStyleSheet("border:0;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(500, 106))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 360, 231, 20))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 270, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 330, 231, 20))
        self.label_7.setObjectName("label_7")
        self.lbl_company = QtWidgets.QLabel(Form)
        self.lbl_company.setGeometry(QtCore.QRect(130, 220, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_company.setFont(font)
        self.lbl_company.setStyleSheet("color:\"#fff44400\";")
        self.lbl_company.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_company.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_company.setLineWidth(1)
        self.lbl_company.setTextFormat(QtCore.Qt.RichText)
        self.lbl_company.setScaledContents(False)
        self.lbl_company.setObjectName("lbl_company")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 300, 141, 17))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(30, 120, 331, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.about_ims = QtWidgets.QLabel(Form)
        self.about_ims.setGeometry(QtCore.QRect(30, 10, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.about_ims.setFont(font)
        self.about_ims.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.about_ims.setToolTip("")
        self.about_ims.setTextFormat(QtCore.Qt.RichText)
        self.about_ims.setObjectName("about_ims")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Version 1.0.0"))
        self.label_6.setText(_translate("Form", "Email: support@bandughana.com"))
        self.label_3.setText(_translate("Form", "This software is copyright protected and \n"
"licensed to "))
        self.label_4.setText(_translate("Form", "Copyright <html >&#169;</html> 2018 Bandugana <i>Inc.</i>"))
        self.label_7.setText(_translate("Form", "Website: <a href=\"https://software.bandughana.com/ims\">www.bandughana.com</a>"))
        self.lbl_company.setText(_translate("Form", "Bandughana"))
        self.label_5.setText(_translate("Form", "Tel: +233547420604"))
        self.about_ims.setText(_translate("Form", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

