# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/about.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(398, 396)
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(About)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.about_ims = QtWidgets.QLabel(About)
        self.about_ims.setGeometry(QtCore.QRect(20, 0, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.about_ims.setFont(font)
        self.about_ims.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.about_ims.setToolTip("")
        self.about_ims.setTextFormat(QtCore.Qt.RichText)
        self.about_ims.setObjectName("about_ims")
        self.label_5 = QtWidgets.QLabel(About)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 141, 17))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(About)
        self.line.setGeometry(QtCore.QRect(20, 110, 331, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(About)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_company = QtWidgets.QLabel(About)
        self.lbl_company.setGeometry(QtCore.QRect(120, 206, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_company.setFont(font)
        self.lbl_company.setStyleSheet("color:\"#fff44400\";")
        self.lbl_company.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_company.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_company.setLineWidth(1)
        self.lbl_company.setTextFormat(QtCore.Qt.RichText)
        self.lbl_company.setScaledContents(False)
        self.lbl_company.setObjectName("lbl_company")
        self.label_7 = QtWidgets.QLabel(About)
        self.label_7.setGeometry(QtCore.QRect(20, 320, 231, 20))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(About)
        self.label_6.setGeometry(QtCore.QRect(20, 350, 231, 20))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(140, 20, 231, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("main.png"))
        self.label.setObjectName("label")
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.lbl_company.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.about_ims.raise_()

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About IMS"))
        self.label_3.setText(_translate("About", "This software is copyright protected and \n"
"licensed to "))
        self.label_4.setText(_translate("About", "Copyright <html >&#169;</html> 2018 Bandugana <i>Inc.</i>"))
        self.about_ims.setText(_translate("About", "About"))
        self.label_5.setText(_translate("About", "Tel: +233547420604"))
        self.label_2.setText(_translate("About", "Version 1.0.0"))
        self.lbl_company.setText(_translate("About", "Ahasaniya Enterprise"))
        self.label_7.setText(_translate("About", "Website: <a href=\"https://software.bandughana.com/ims\">www.bandughana.com</a>"))
        self.label_6.setText(_translate("About", "Email: support@bandughana.com"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    About = QtWidgets.QDialog()
    ui = Ui_About()
    ui.setupUi(About)
    About.show()
    sys.exit(app.exec_())

