# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql

class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(1073, 612)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Analysis.sizePolicy().hasHeightForWidth())
        Analysis.setSizePolicy(sizePolicy)
        Analysis.setMaximumSize(QtCore.QSize(1073, 612))
        self.label = QtWidgets.QLabel(Analysis)
        self.label.setGeometry(QtCore.QRect(0, 0, 1081, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(Analysis)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 130, 411, 221))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("border:1px solid #ccc;\n"
"border-radius:3px;")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lblProfit = QtWidgets.QLabel(self.groupBox_5)
        self.lblProfit.setGeometry(QtCore.QRect(10, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblProfit.setFont(font)
        self.lblProfit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 0);")
        self.lblProfit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblProfit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblProfit.setScaledContents(True)
        self.lblProfit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblProfit.setObjectName("lblProfit")
        self.lblLoss = QtWidgets.QLabel(self.groupBox_5)
        self.lblLoss.setGeometry(QtCore.QRect(210, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblLoss.setFont(font)
        self.lblLoss.setStyleSheet("color:#fff;\n"
"background-color: rgb(255, 0, 0);")
        self.lblLoss.setScaledContents(True)
        self.lblLoss.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLoss.setWordWrap(True)
        self.lblLoss.setObjectName("lblLoss")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#fff;border:0;")
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(240, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#fff;border:0;")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.groupBox_6 = QtWidgets.QGroupBox(Analysis)
        self.groupBox_6.setGeometry(QtCore.QRect(430, 130, 411, 221))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("border:1px solid #ccc;\n"
"border-radius:3px;")
        self.groupBox_6.setObjectName("groupBox_6")
        self.lblOutwards = QtWidgets.QLabel(self.groupBox_6)
        self.lblOutwards.setGeometry(QtCore.QRect(10, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblOutwards.setFont(font)
        self.lblOutwards.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.lblOutwards.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblOutwards.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblOutwards.setScaledContents(True)
        self.lblOutwards.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOutwards.setObjectName("lblOutwards")
        self.lblInwards = QtWidgets.QLabel(self.groupBox_6)
        self.lblInwards.setGeometry(QtCore.QRect(210, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblInwards.setFont(font)
        self.lblInwards.setStyleSheet("color:#fff;\n"
"background-color: rgb(255, 0, 127);")
        self.lblInwards.setScaledContents(True)
        self.lblInwards.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInwards.setWordWrap(True)
        self.lblInwards.setObjectName("lblInwards")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(240, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#fff;border:0;")
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(40, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:#fff;border:0;")
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.groupBox = QtWidgets.QGroupBox(Analysis)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 691, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border:1px solid #ccc; border-radius:3px;")
        self.groupBox.setObjectName("groupBox")
        self.btnLoad = QtWidgets.QPushButton(self.groupBox)
        self.btnLoad.setGeometry(QtCore.QRect(610, 30, 71, 31))
        self.btnLoad.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border:0;\n"
"color: rgb(255, 255, 255);")
        self.btnLoad.setObjectName("btnLoad")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(9, 30, 65, 21))
        self.label_8.setStyleSheet("border:0;")
        self.label_8.setObjectName("label_8")
        self.startDate = QtWidgets.QDateEdit(self.groupBox)
        self.startDate.setGeometry(QtCore.QRect(80, 30, 231, 31))
        self.startDate.setDate(QtCore.QDate(2018, 6, 14))
        self.startDate.setMinimumDate(QtCore.QDate(2018, 6, 14))
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(330, 30, 32, 21))
        self.label_7.setStyleSheet("border:0;")
        self.label_7.setObjectName("label_7")
        self.endDate = QtWidgets.QDateEdit(Analysis)
        self.endDate.setGeometry(QtCore.QRect(380, 80, 231, 31))
        self.endDate.setMinimumDate(QtCore.QDate(2018, 6, 22))
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.groupBox_2 = QtWidgets.QGroupBox(Analysis)
        self.groupBox_2.setGeometry(QtCore.QRect(720, 50, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border:1px solid #ccc; border-radius:3px;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.filterDay = QtWidgets.QDateEdit(self.groupBox_2)
        self.filterDay.setGeometry(QtCore.QRect(20, 30, 231, 31))
        self.filterDay.setMinimumDate(QtCore.QDate(2018, 6, 22))
        self.filterDay.setCalendarPopup(True)
        self.filterDay.setObjectName("filterDay")
        self.btnFilter = QtWidgets.QPushButton(Analysis)
        self.btnFilter.setGeometry(QtCore.QRect(980, 80, 71, 31))
        self.btnFilter.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border:0;\n"
"color: rgb(255, 255, 255);")
        self.btnFilter.setObjectName("btnFilter")
        self.groupBox_7 = QtWidgets.QGroupBox(Analysis)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 360, 611, 221))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("border:1px solid #ccc;\n"
"border-radius:3px;")
        self.groupBox_7.setObjectName("groupBox_7")
        self.lblInStock = QtWidgets.QLabel(self.groupBox_7)
        self.lblInStock.setGeometry(QtCore.QRect(10, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblInStock.setFont(font)
        self.lblInStock.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(171, 171, 0);")
        self.lblInStock.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblInStock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblInStock.setScaledContents(True)
        self.lblInStock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInStock.setObjectName("lblInStock")
        self.lblOutStock = QtWidgets.QLabel(self.groupBox_7)
        self.lblOutStock.setGeometry(QtCore.QRect(210, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblOutStock.setFont(font)
        self.lblOutStock.setStyleSheet("color:#fff;\n"
"background-color: rgb(170, 0, 0);")
        self.lblOutStock.setScaledContents(True)
        self.lblOutStock.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOutStock.setWordWrap(True)
        self.lblOutStock.setObjectName("lblOutStock")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(240, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:#fff;border:0;")
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(40, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:#fff;border:0;")
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lblTotal = QtWidgets.QLabel(self.groupBox_7)
        self.lblTotal.setGeometry(QtCore.QRect(410, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotal.setFont(font)
        self.lblTotal.setStyleSheet("color:#fff;\n"
"background-color: rgb(170, 0, 127);")
        self.lblTotal.setScaledContents(True)
        self.lblTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTotal.setWordWrap(True)
        self.lblTotal.setObjectName("lblTotal")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(440, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:#fff;border:0;")
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.groupBox_8 = QtWidgets.QGroupBox(Analysis)
        self.groupBox_8.setGeometry(QtCore.QRect(630, 360, 211, 221))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("border:1px solid #ccc;\n"
"border-radius:3px;")
        self.groupBox_8.setObjectName("groupBox_8")
        self.lblDebtors = QtWidgets.QLabel(self.groupBox_8)
        self.lblDebtors.setGeometry(QtCore.QRect(10, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblDebtors.setFont(font)
        self.lblDebtors.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.lblDebtors.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblDebtors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblDebtors.setScaledContents(True)
        self.lblDebtors.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDebtors.setObjectName("lblDebtors")
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(40, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:#fff;border:0;")
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(240, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#fff;border:0;")
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.groupBox_9 = QtWidgets.QGroupBox(Analysis)
        self.groupBox_9.setGeometry(QtCore.QRect(850, 130, 211, 451))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("border:1px solid #ccc;\n"
"border-radius:3px;")
        self.groupBox_9.setObjectName("groupBox_9")
        self.lblSuppliers = QtWidgets.QLabel(self.groupBox_9)
        self.lblSuppliers.setGeometry(QtCore.QRect(10, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblSuppliers.setFont(font)
        self.lblSuppliers.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.lblSuppliers.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblSuppliers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblSuppliers.setScaledContents(True)
        self.lblSuppliers.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSuppliers.setObjectName("lblSuppliers")
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        self.label_19.setGeometry(QtCore.QRect(40, 400, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:#fff;border:0;")
        self.label_19.setScaledContents(True)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        self.label_20.setGeometry(QtCore.QRect(40, 170, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:#fff;border:0;")
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.lblCustomers = QtWidgets.QLabel(self.groupBox_9)
        self.lblCustomers.setGeometry(QtCore.QRect(10, 250, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblCustomers.setFont(font)
        self.lblCustomers.setStyleSheet("color:#fff;\n"
"background-color: rgb(255, 0, 127);")
        self.lblCustomers.setScaledContents(True)
        self.lblCustomers.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCustomers.setWordWrap(True)
        self.lblCustomers.setObjectName("lblCustomers")
        self.lblCustomers.raise_()
        self.lblSuppliers.raise_()
        self.label_19.raise_()
        self.label_20.raise_()

        self.retranslateUi(Analysis)
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, Analysis):
        _translate = QtCore.QCoreApplication.translate
        Analysis.setWindowTitle(_translate("Analysis", "Store Analytics"))
        self.label.setText(_translate("Analysis", "Store Analytics And Statistics"))
        self.groupBox_5.setTitle(_translate("Analysis", "Profit and Loss"))
        self.lblProfit.setText(_translate("Analysis", "3002.34"))
        self.lblLoss.setText(_translate("Analysis", "-285.89"))
        self.label_4.setText(_translate("Analysis", "Total Profit"))
        self.label_5.setText(_translate("Analysis", "Total Loss"))
        self.groupBox_6.setTitle(_translate("Analysis", "Returns"))
        self.lblOutwards.setText(_translate("Analysis", "23"))
        self.lblInwards.setText(_translate("Analysis", "190"))
        self.label_6.setText(_translate("Analysis", "Inwards"))
        self.label_9.setText(_translate("Analysis", "Outwards"))
        self.groupBox.setTitle(_translate("Analysis", "Choose Range"))
        self.btnLoad.setText(_translate("Analysis", "Load"))
        self.label_8.setText(_translate("Analysis", "Between:"))
        self.label_7.setText(_translate("Analysis", "And:"))
        self.groupBox_2.setTitle(_translate("Analysis", "Filter by day"))
        self.btnFilter.setText(_translate("Analysis", "Filter"))
        self.groupBox_7.setTitle(_translate("Analysis", "Products"))
        self.lblInStock.setText(_translate("Analysis", "2300"))
        self.lblOutStock.setText(_translate("Analysis", "20"))
        self.label_10.setText(_translate("Analysis", "Out of Stock"))
        self.label_11.setText(_translate("Analysis", "In Stock"))
        self.lblTotal.setText(_translate("Analysis", "2320"))
        self.label_12.setText(_translate("Analysis", "Total"))
        self.groupBox_8.setTitle(_translate("Analysis", "Debtors"))
        self.lblDebtors.setText(_translate("Analysis", "3"))
        self.label_13.setText(_translate("Analysis", "Debtors"))
        self.label_14.setText(_translate("Analysis", "Total Loss"))
        self.groupBox_9.setTitle(_translate("Analysis", "Suppliers and Customers"))
        self.lblSuppliers.setText(_translate("Analysis", "23"))
        self.label_19.setText(_translate("Analysis", "Customers"))
        self.label_20.setText(_translate("Analysis", "Suppliers"))
        self.lblCustomers.setText(_translate("Analysis", "190"))



def get_total(table):
    import sql
    from functions import num_rows
    if sql.connectDB():
        query = QtSql.QSqlQuery()
        query.exec_("SELECT id FROM {0}".format(str(table)))
        if num_rows(query) == -1:
            rows = 0
        else:
            rows = num_rows(query)
        return rows


def get_greater_total(table, constraint, value):
    import sql
    from functions import num_rows
    if sql.connectDB():
        query = QtSql.QSqlQuery()
        query.exec_("SELECT * FROM {0} WHERE {1} > {2}".format(str(table),str(constraint), value))
        if num_rows(query) == -1:
            rows = 0
        else:
            rows = num_rows(query)
        return rows


def get_lesser_total(table, constraint, value):
    import sql
    from functions import num_rows
    if sql.connectDB():
        query = QtSql.QSqlQuery()
        query.exec_("SELECT * FROM {0} WHERE {1} < {2}".format(str(table),str(constraint), value))
        if num_rows(query) == -1:
            rows = 0
        else:
            rows = num_rows(query)
        return rows


def get_constraint_total(table, key, value):
    import sql
    from functions import num_rows
    if sql.connectDB():
        query = QtSql.QSqlQuery()
        query.exec_("SELECT * FROM {0} WHERE {1} = {2}".format(str(table), str(key), str(value)))
        if num_rows(query) == -1:
            rows = 0
        else:
            rows = num_rows(query)
        return rows


def mainMan():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Analysis = QtWidgets.QWidget()
        ui = Ui_Analysis()
        ui.setupUi(Analysis)
        ui.lblDebtors.setText(str(get_total("debts")))
        ui.lblInStock.setText(str(get_greater_total("stock", "quantity", 0)))
        ui.lblOutStock.setText(str(get_lesser_total("stock", "quantity", 1)))
        ui.lblTotal.setText(str(get_total("products")))
        ui.lblCustomers.setText(str(get_total("customers")))
        ui.lblSuppliers.setText(str(get_total("suppliers")))
        ui.lblOutwards.setText(str(get_constraint_total("returns", "return_type", "outward")))
        ui.lblInwards.setText(str(get_constraint_total("returns", "return_type", "inward")))
        Analysis.setGeometry(130, 20, 1073, 612)
        Analysis.show()
        sys.exit(app.exec_())