# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editproduct.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditProduct(object):
    def setupUi(self, EditProduct):
        EditProduct.setObjectName("EditProduct")
        EditProduct.resize(516, 530)
        self.label = QtWidgets.QLabel(EditProduct)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(EditProduct)
        self.comboBox.setGeometry(QtCore.QRect(150, 56, 301, 27))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(EditProduct)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 111, 17))
        self.label_3.setObjectName("label_3")
        self.btnRefresh = QtWidgets.QPushButton(EditProduct)
        self.btnRefresh.setGeometry(QtCore.QRect(450, 56, 31, 27))
        self.btnRefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/Apply_16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon)
        self.btnRefresh.setObjectName("btnRefresh")
        self.hideBox = QtWidgets.QGroupBox(EditProduct)
        self.hideBox.setEnabled(False)
        self.hideBox.setGeometry(QtCore.QRect(-10, 70, 551, 451))
        self.hideBox.setTitle("")
        self.hideBox.setObjectName("hideBox")
        self.lblTotal = QtWidgets.QLabel(self.hideBox)
        self.lblTotal.setGeometry(QtCore.QRect(30, 280, 51, 27))
        self.lblTotal.setObjectName("lblTotal")
        self.lblDate = QtWidgets.QLabel(self.hideBox)
        self.lblDate.setGeometry(QtCore.QRect(250, 280, 41, 27))
        self.lblDate.setObjectName("lblDate")
        self.lblRealPrice = QtWidgets.QLabel(self.hideBox)
        self.lblRealPrice.setGeometry(QtCore.QRect(30, 180, 92, 27))
        self.lblRealPrice.setToolTip("")
        self.lblRealPrice.setProperty("toolTipDuration", 2)
        self.lblRealPrice.setObjectName("lblRealPrice")
        self.lblSalePrice = QtWidgets.QLabel(self.hideBox)
        self.lblSalePrice.setGeometry(QtCore.QRect(30, 230, 81, 27))
        self.lblSalePrice.setObjectName("lblSalePrice")
        self.lblQuantity = QtWidgets.QLabel(self.hideBox)
        self.lblQuantity.setGeometry(QtCore.QRect(30, 130, 64, 27))
        self.lblQuantity.setObjectName("lblQuantity")
        self.realPrice = QtWidgets.QLineEdit(self.hideBox)
        self.realPrice.setGeometry(QtCore.QRect(130, 180, 311, 27))
        self.realPrice.setObjectName("realPrice")
        self.productCode = QtWidgets.QLineEdit(self.hideBox)
        self.productCode.setGeometry(QtCore.QRect(140, 80, 301, 27))
        self.productCode.setObjectName("productCode")
        self.productName = QtWidgets.QLineEdit(self.hideBox)
        self.productName.setGeometry(QtCore.QRect(140, 30, 301, 27))
        self.productName.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.productName.setObjectName("productName")
        self.lblProductName = QtWidgets.QLabel(self.hideBox)
        self.lblProductName.setGeometry(QtCore.QRect(30, 30, 102, 27))
        self.lblProductName.setObjectName("lblProductName")
        self.btnSave = QtWidgets.QPushButton(self.hideBox)
        self.btnSave.setGeometry(QtCore.QRect(310, 394, 81, 31))
        self.btnSave.setStyleSheet("background-color: rgb(0, 0, 175);\n"
"color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"selection-background-color: rgb(0, 0, 232);")
        self.btnSave.setObjectName("btnSave")
        self.quantity = QtWidgets.QLineEdit(self.hideBox)
        self.quantity.setGeometry(QtCore.QRect(100, 130, 121, 27))
        self.quantity.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.quantity.setObjectName("quantity")
        self.total = QtWidgets.QLineEdit(self.hideBox)
        self.total.setGeometry(QtCore.QRect(70, 280, 171, 27))
        self.total.setObjectName("total")
        self.lblSupplier = QtWidgets.QLabel(self.hideBox)
        self.lblSupplier.setGeometry(QtCore.QRect(30, 330, 61, 27))
        self.lblSupplier.setObjectName("lblSupplier")
        self.btnAddSupplier = QtWidgets.QPushButton(self.hideBox)
        self.btnAddSupplier.setGeometry(QtCore.QRect(400, 330, 41, 27))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddSupplier.setFont(font)
        self.btnAddSupplier.setStyleSheet("color:#f64")
        self.btnAddSupplier.setAutoDefault(True)
        self.btnAddSupplier.setDefault(False)
        self.btnAddSupplier.setObjectName("btnAddSupplier")
        self.lblProductCode = QtWidgets.QLabel(self.hideBox)
        self.lblProductCode.setGeometry(QtCore.QRect(30, 80, 111, 27))
        self.lblProductCode.setObjectName("lblProductCode")
        self.category = QtWidgets.QComboBox(self.hideBox)
        self.category.setGeometry(QtCore.QRect(310, 130, 131, 27))
        self.category.setObjectName("category")
        self.supplier = QtWidgets.QComboBox(self.hideBox)
        self.supplier.setGeometry(QtCore.QRect(104, 330, 281, 27))
        self.supplier.setObjectName("supplier")
        self.salePrice = QtWidgets.QLineEdit(self.hideBox)
        self.salePrice.setGeometry(QtCore.QRect(130, 230, 311, 27))
        self.salePrice.setObjectName("salePrice")
        self.btnCancel = QtWidgets.QPushButton(self.hideBox)
        self.btnCancel.setGeometry(QtCore.QRect(60, 394, 99, 31))
        self.btnCancel.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnCancel.setObjectName("btnCancel")
        self.dateAdded = QtWidgets.QDateEdit(self.hideBox)
        self.dateAdded.setGeometry(QtCore.QRect(300, 280, 141, 27))
        self.dateAdded.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateAdded.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateAdded.setMinimumDate(QtCore.QDate(2018, 6, 20))
        self.dateAdded.setCalendarPopup(True)
        self.dateAdded.setObjectName("dateAdded")
        self.label_2 = QtWidgets.QLabel(self.hideBox)
        self.label_2.setGeometry(QtCore.QRect(240, 134, 68, 17))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(EditProduct)
        QtCore.QMetaObject.connectSlotsByName(EditProduct)

    def retranslateUi(self, EditProduct):
        _translate = QtCore.QCoreApplication.translate
        EditProduct.setWindowTitle(_translate("EditProduct", "Edit Product"))
        self.label.setText(_translate("EditProduct", "Edit Product"))
        self.label_3.setText(_translate("EditProduct", "Select product:"))
        self.lblTotal.setText(_translate("EditProduct", "Total:"))
        self.lblDate.setText(_translate("EditProduct", "Date:"))
        self.lblRealPrice.setText(_translate("EditProduct", "Real Price:"))
        self.lblSalePrice.setText(_translate("EditProduct", "Sale Price:"))
        self.lblQuantity.setText(_translate("EditProduct", "Quantity:"))
        self.lblProductName.setText(_translate("EditProduct", "Product Name:"))
        self.btnSave.setText(_translate("EditProduct", "Save"))
        self.lblSupplier.setText(_translate("EditProduct", "Supplier:"))
        self.btnAddSupplier.setToolTip(_translate("EditProduct", "Add new supplier"))
        self.btnAddSupplier.setText(_translate("EditProduct", "+"))
        self.lblProductCode.setText(_translate("EditProduct", "Produc Code:"))
        self.btnCancel.setText(_translate("EditProduct", "Cancel"))
        self.label_2.setText(_translate("EditProduct", "Category:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditProduct = QtWidgets.QDialog()
    ui = Ui_EditProduct()
    ui.setupUi(EditProduct)
    EditProduct.show()
    sys.exit(app.exec_())

