# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editcreditors.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import sql
class Ui_Creditors(object):
    def setupUi(self, Creditors):
        Creditors.setObjectName("Creditors")
        Creditors.resize(1024, 583)
        Creditors.setMaximumSize(QtCore.QSize(1024, 585))
        self.groupBox = QtWidgets.QGroupBox(Creditors)
        self.groupBox.setGeometry(QtCore.QRect(230, -10, 771, 91))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnSearch = QtWidgets.QPushButton(self.groupBox)
        self.btnSearch.setGeometry(QtCore.QRect(380, 40, 99, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.search = QtWidgets.QLineEdit(self.groupBox)
        self.search.setGeometry(QtCore.QRect(20, 40, 361, 31))
        self.search.setObjectName("search")
        self.btnDelete = QtWidgets.QPushButton(self.groupBox)
        self.btnDelete.setGeometry(QtCore.QRect(660, 40, 81, 31))
        self.btnDelete.setStyleSheet("")
        self.btnDelete.setObjectName("btnDelete")
        self.btnNewCreditor = QtWidgets.QPushButton(self.groupBox)
        self.btnNewCreditor.setGeometry(QtCore.QRect(510, 40, 121, 31))
        self.btnNewCreditor.setStyleSheet("")
        self.btnNewCreditor.setObjectName("btnNewCreditor")
        self.creditorView = QtWidgets.QTableView(Creditors)
        self.creditorView.setGeometry(QtCore.QRect(230, 80, 771, 441))
        self.creditorView.setObjectName("creditorView")
        self.btnClose = QtWidgets.QPushButton(Creditors)
        self.btnClose.setGeometry(QtCore.QRect(900, 530, 99, 41))
        self.btnClose.setObjectName("btnClose")
        self.formGroupBox = QtWidgets.QGroupBox(Creditors)
        self.formGroupBox.setGeometry(QtCore.QRect(30, -10, 181, 531))
        self.formGroupBox.setTitle("")
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(self.formGroupBox)
        self.name.setObjectName("name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.name)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.phone = QtWidgets.QLineEdit(self.formGroupBox)
        self.phone.setObjectName("phone")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.phone)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.product = QtWidgets.QLineEdit(self.formGroupBox)
        self.product.setObjectName("product")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.product)
        self.label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.amountPaid = QtWidgets.QLineEdit(self.formGroupBox)
        self.amountPaid.setObjectName("amountPaid")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.amountPaid)
        self.label_5 = QtWidgets.QLabel(self.formGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.amountOwed = QtWidgets.QLineEdit(self.formGroupBox)
        self.amountOwed.setObjectName("amountOwed")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.amountOwed)
        self.label_6 = QtWidgets.QLabel(self.formGroupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.total = QtWidgets.QLineEdit(self.formGroupBox)
        self.total.setObjectName("total")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.total)
        self.label_7 = QtWidgets.QLabel(self.formGroupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.quantity = QtWidgets.QLineEdit(self.formGroupBox)
        self.quantity.setObjectName("quantity")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.quantity)
        self.label_8 = QtWidgets.QLabel(self.formGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dueDate = QtWidgets.QLineEdit(self.formGroupBox)
        self.dueDate.setObjectName("dueDate")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.dueDate)
        self.label_9 = QtWidgets.QLabel(self.formGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.id = QtWidgets.QLineEdit(self.formGroupBox)
        self.id.setObjectName("id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.id)
        self.btnEdit = QtWidgets.QPushButton(Creditors)
        self.btnEdit.setGeometry(QtCore.QRect(40, 540, 141, 31))
        self.btnEdit.setStyleSheet("")
        self.btnEdit.setObjectName("btnEdit")

        self.retranslateUi(Creditors)
        self.btnClose.clicked.connect(Creditors.close)
        QtCore.QMetaObject.connectSlotsByName(Creditors)

    def retranslateUi(self, Creditors):
        _translate = QtCore.QCoreApplication.translate
        Creditors.setWindowTitle(_translate("Creditors", "Creditors"))
        self.btnSearch.setText(_translate("Creditors", "Search"))
        self.btnDelete.setText(_translate("Creditors", "Delete"))
        self.btnNewCreditor.setText(_translate("Creditors", "New Creditor"))
        self.btnClose.setText(_translate("Creditors", "Close"))
        self.label.setText(_translate("Creditors", "Name:"))
        self.label_2.setText(_translate("Creditors", "Phone:"))
        self.label_3.setText(_translate("Creditors", "Product:"))
        self.label_4.setText(_translate("Creditors", "Amount Paid:"))
        self.label_5.setText(_translate("Creditors", "Amount Owed:"))
        self.label_6.setText(_translate("Creditors", "Total:"))
        self.label_7.setText(_translate("Creditors", "Quantity:"))
        self.label_8.setText(_translate("Creditors", "Due Date:"))
        self.label_9.setText(_translate("Creditors", "ID:"))
        self.btnEdit.setText(_translate("Creditors", "Update Selected"))


    def display_creditors(self):
        sql.connectDB()
        self.model = QtSql.QSqlTableModel()
        self.model.setTable("creditors")
        self.model.setHeaderData(0, QtCore.Qt.Horizontal, "ID")
        self.model.setHeaderData(1, QtCore.Qt.Horizontal, "Name")
        self.model.setHeaderData(2, QtCore.Qt.Horizontal, "Phone")
        self.model.setHeaderData(3, QtCore.Qt.Horizontal, "Product")
        self.model.setHeaderData(4, QtCore.Qt.Horizontal, "Amount Paid")
        self.model.setHeaderData(5, QtCore.Qt.Horizontal, "Amount Owed")
        self.model.setHeaderData(6, QtCore.Qt.Horizontal, "Total")
        self.model.setHeaderData(7, QtCore.Qt.Horizontal, "Quantity")
        self.model.setHeaderData(8, QtCore.Qt.Horizontal, "Due Date")
        self.model.select()
        self.creditorView.setModel(self.model)
        self.creditorView.horizontalHeader().setMinimumHeight(40)
        self.creditorView.horizontalHeader().setStyleSheet("background-color:#222;color:#dadada;")
        self.creditorView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.creditorView.horizontalHeader().setDefaultSectionSize(120)
        self.creditorView.setColumnHidden(0, True)
        self.creditorView.show()

    def get_creditor(self):

        if self.search_query.text() == '' or self.search_query.text().isspace():
            QtWidgets.QMessageBox.critical(None, QtWidgets.qApp.tr("Enter search query"), QtWidgets.qApp.tr(
                "Please enter search criterion to search!"), QtWidgets.QMessageBox.Ok)
        else:
            qry = QtSql.QSqlQuery()
            qry.prepare("select * from creditors where creditor_name LIKE '%{0}%' or product_name LIKE '%{0}%' or "
                        "due_date LIKE '%{0}%'".format(str(self.search_query.text())))

            if qry.exec_():
                self.model = QtSql.QSqlQueryModel()
                self.model.setQuery(qry)
                self.model.setHeaderData(0, QtCore.Qt.Horizontal, "ID")
                self.model.setHeaderData(1, QtCore.Qt.Horizontal, "Name")
                self.model.setHeaderData(2, QtCore.Qt.Horizontal, "Phone")
                self.model.setHeaderData(3, QtCore.Qt.Horizontal, "Product")
                self.model.setHeaderData(4, QtCore.Qt.Horizontal, "Amount Paid")
                self.model.setHeaderData(5, QtCore.Qt.Horizontal, "Amount Owed")
                self.model.setHeaderData(6, QtCore.Qt.Horizontal, "Total")
                self.model.setHeaderData(7, QtCore.Qt.Horizontal, "Quantity")
                self.model.setHeaderData(8, QtCore.Qt.Horizontal, "Due")
                self.model.select()
                self.creditorView.setModel(self.model)
                self.creditorView.horizontalHeader().setMinimumHeight(40)
                self.creditorView.horizontalHeader().setStyleSheet("background-color:#222;color:#dadada;")
                self.creditorView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
                self.creditorView.setColumnHidden(0, True)
                self.creditorView.show()
                self.creditorView.setModel(self.model)
                self.creditorView.setColumnHidden(0, True)
                self.creditorView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
                self.creditorView.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Creditors = QtWidgets.QDialog()
    ui = Ui_Creditors()
    ui.setupUi(Creditors)
    ui.id.setDisabled(True)
    ui.display_creditors()
    Creditors.show()
    sys.exit(app.exec_())