# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editdebtors.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import sql

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(982, 622)
        self.debtorView = QtWidgets.QTableView(Dialog)
        self.debtorView.setGeometry(QtCore.QRect(240, 100, 711, 431))
        self.debtorView.setObjectName("debtorView")
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setGeometry(QtCore.QRect(840, 560, 99, 41))
        self.btnClose.setObjectName("btnClose")
        self.EditDebtors = QtWidgets.QGroupBox(Dialog)
        self.EditDebtors.setGeometry(QtCore.QRect(240, 10, 711, 91))
        self.EditDebtors.setStyleSheet("")
        self.EditDebtors.setTitle("")
        self.EditDebtors.setObjectName("EditDebtors")
        self.btnSearch = QtWidgets.QPushButton(self.EditDebtors)
        self.btnSearch.setGeometry(QtCore.QRect(320, 30, 99, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.search = QtWidgets.QLineEdit(self.EditDebtors)
        self.search.setGeometry(QtCore.QRect(20, 30, 301, 31))
        self.search.setObjectName("search")
        self.btnNewDebtor = QtWidgets.QPushButton(self.EditDebtors)
        self.btnNewDebtor.setGeometry(QtCore.QRect(430, 30, 121, 31))
        self.btnNewDebtor.setStyleSheet("")
        self.btnNewDebtor.setObjectName("btnNewDebtor")
        self.btnDelete = QtWidgets.QPushButton(self.EditDebtors)
        self.btnDelete.setGeometry(QtCore.QRect(570, 30, 111, 31))
        self.btnDelete.setStyleSheet("")
        self.btnDelete.setObjectName("btnDelete")
        self.btnEdit = QtWidgets.QPushButton(Dialog)
        self.btnEdit.setGeometry(QtCore.QRect(680, 560, 121, 41))
        self.btnEdit.setStyleSheet("")
        self.btnEdit.setObjectName("btnEdit")
        self.formGroupBox = QtWidgets.QGroupBox(Dialog)
        self.formGroupBox.setGeometry(QtCore.QRect(40, 10, 181, 541))
        self.formGroupBox.setTitle("")
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.formGroupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.id = QtWidgets.QLineEdit(self.formGroupBox)
        self.id.setObjectName("id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.id)
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(self.formGroupBox)
        self.name.setObjectName("name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.name)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.phone = QtWidgets.QLineEdit(self.formGroupBox)
        self.phone.setObjectName("phone")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.phone)
        self.label_9 = QtWidgets.QLabel(self.formGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.city = QtWidgets.QLineEdit(self.formGroupBox)
        self.city.setObjectName("city")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.city)
        self.label_10 = QtWidgets.QLabel(self.formGroupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.area = QtWidgets.QLineEdit(self.formGroupBox)
        self.area.setObjectName("area")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.area)
        self.label_11 = QtWidgets.QLabel(self.formGroupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.address = QtWidgets.QTextEdit(self.formGroupBox)
        self.address.setMaximumSize(QtCore.QSize(142, 80))
        self.address.setObjectName("address")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.address)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.product = QtWidgets.QLineEdit(self.formGroupBox)
        self.product.setObjectName("product")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.product)
        self.label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.amountPaid = QtWidgets.QLineEdit(self.formGroupBox)
        self.amountPaid.setObjectName("amountPaid")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.amountPaid)
        self.label_5 = QtWidgets.QLabel(self.formGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.amountOwed = QtWidgets.QLineEdit(self.formGroupBox)
        self.amountOwed.setObjectName("amountOwed")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.amountOwed)
        self.horizontalGroupBox = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox.setGeometry(QtCore.QRect(40, 530, 621, 81))
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setContentsMargins(16, -1, 21, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.total = QtWidgets.QLineEdit(self.horizontalGroupBox)
        self.total.setObjectName("total")
        self.horizontalLayout.addWidget(self.total)
        self.label_7 = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.dueDate = QtWidgets.QLineEdit(self.horizontalGroupBox)
        self.dueDate.setObjectName("dueDate")
        self.horizontalLayout.addWidget(self.dueDate)
        self.label_8 = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.quantity = QtWidgets.QLineEdit(self.horizontalGroupBox)
        self.quantity.setObjectName("quantity")
        self.horizontalLayout.addWidget(self.quantity)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit debtor information"))
        self.btnClose.setText(_translate("Dialog", "Close"))
        self.btnSearch.setText(_translate("Dialog", "Search"))
        self.btnNewDebtor.setText(_translate("Dialog", "New Debtor"))
        self.btnDelete.setText(_translate("Dialog", "Delete"))
        self.btnEdit.setText(_translate("Dialog", "Update Debtor"))
        self.label_12.setText(_translate("Dialog", "ID:"))
        self.label.setText(_translate("Dialog", "Name:"))
        self.label_2.setText(_translate("Dialog", "Phone:"))
        self.label_9.setText(_translate("Dialog", "City:"))
        self.label_10.setText(_translate("Dialog", "Area:"))
        self.label_11.setText(_translate("Dialog", "Address:"))
        self.label_3.setText(_translate("Dialog", "Product:"))
        self.label_4.setText(_translate("Dialog", "Amount Paid:"))
        self.label_5.setText(_translate("Dialog", "Amount Owed:"))
        self.label_6.setText(_translate("Dialog", "Total:"))
        self.label_7.setText(_translate("Dialog", "Quantity:"))
        self.label_8.setText(_translate("Dialog", "Due Date:"))

    def display_debtors(self):
        sql.connectDB()
        self.model = QtSql.QSqlTableModel()
        self.model.setTable("debts")
        self.model.setHeaderData(0, QtCore.Qt.Horizontal, "ID")
        self.model.setHeaderData(1, QtCore.Qt.Horizontal, "Name")
        self.model.setHeaderData(2, QtCore.Qt.Horizontal, "Phone")
        self.model.setHeaderData(3, QtCore.Qt.Horizontal, "City")
        self.model.setHeaderData(4, QtCore.Qt.Horizontal, "Area")
        self.model.setHeaderData(5, QtCore.Qt.Horizontal, "Address")
        self.model.setHeaderData(6, QtCore.Qt.Horizontal, "Product")
        self.model.setHeaderData(7, QtCore.Qt.Horizontal, "Paid")
        self.model.setHeaderData(8, QtCore.Qt.Horizontal, "Owed")
        self.model.setHeaderData(9, QtCore.Qt.Horizontal, "Total")
        self.model.setHeaderData(10, QtCore.Qt.Horizontal, "Quantity")
        self.model.setHeaderData(11, QtCore.Qt.Horizontal, "Due Date")
        self.model.select()
        self.debtorView.setModel(self.model)
        self.debtorView.horizontalHeader().setMinimumHeight(40)
        self.debtorView.horizontalHeader().setStyleSheet("background-color:#222;color:#dadada;")
        self.debtorView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.debtorView.setColumnHidden(0, True)
        self.debtorView.show()

    def get_debtor(self):

        if self.search.text() == '' or self.search.text().isspace():
            QtWidgets.QMessageBox.critical(None, QtWidgets.qApp.tr("Enter search query"), QtWidgets.qApp.tr(
                "Please enter search criterion to search!"), QtWidgets.QMessageBox.Ok)
        else:
            qry = QtSql.QSqlQuery()
            qry.prepare("select * from debts where customer_name LIKE '%{0}%' or product_name LIKE '%{0}%' or "
                        "city LIKE '%{0}%' or area LIKE '%{0}%' or address LIKE '%{0}%' or due_date LIKE '%{0}%'".format(
                str(self.search.text())))
            # qry.bindValue(0, str(self.search.text()))
            if qry.exec_():
                my_model = QtSql.QSqlQueryModel()
                my_model.setQuery(qry)
                my_model.setHeaderData(0, QtCore.Qt.Horizontal, "ID")
                my_model.setHeaderData(1, QtCore.Qt.Horizontal, "Name")
                my_model.setHeaderData(2, QtCore.Qt.Horizontal, "Phone")
                my_model.setHeaderData(3, QtCore.Qt.Horizontal, "City")
                my_model.setHeaderData(4, QtCore.Qt.Horizontal, "Area")
                my_model.setHeaderData(5, QtCore.Qt.Horizontal, "Address")
                my_model.setHeaderData(6, QtCore.Qt.Horizontal, "Product")
                my_model.setHeaderData(7, QtCore.Qt.Horizontal, "Paid")
                my_model.setHeaderData(8, QtCore.Qt.Horizontal, "Owed")
                my_model.setHeaderData(9, QtCore.Qt.Horizontal, "Total")
                my_model.setHeaderData(10, QtCore.Qt.Horizontal, "Quantity")
                my_model.setHeaderData(11, QtCore.Qt.Horizontal, "Due Date")
                self.debtorView.setModel(my_model)
                self.debtorView.setColumnHidden(0, True)
                self.debtorView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
                self.debtorView.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.id.setDisabled(True)
    ui.display_debtors()
    ui.btnSearch.clicked.connect(ui.get_debtor)
    Dialog.show()
    sys.exit(app.exec_())

