# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formproduct.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from time import strftime, gmtime

class Ui_FormProduct(object):
    def setupUi(self, FormProduct):
        FormProduct.setObjectName("FormProduct")
        FormProduct.resize(470, 467)
        self.productName = QtWidgets.QLineEdit(FormProduct)
        self.productName.setGeometry(QtCore.QRect(130, 60, 301, 27))
        self.productName.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.productName.setObjectName("productName")
        self.btnSave = QtWidgets.QPushButton(FormProduct)
        self.btnSave.setGeometry(QtCore.QRect(310, 410, 81, 31))
        self.btnSave.setStyleSheet("background-color: rgb(0, 0, 175);\n"
"color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 255);\n"
"selection-background-color: rgb(0, 0, 232);")
        self.btnSave.setObjectName("btnSave")
        self.lblTotal = QtWidgets.QLabel(FormProduct)
        self.lblTotal.setGeometry(QtCore.QRect(20, 310, 51, 27))
        self.lblTotal.setObjectName("lblTotal")
        self.lblProductCode = QtWidgets.QLabel(FormProduct)
        self.lblProductCode.setGeometry(QtCore.QRect(20, 110, 111, 27))
        self.lblProductCode.setObjectName("lblProductCode")
        self.dateAdded = QtWidgets.QDateEdit(FormProduct)
        self.dateAdded.setGeometry(QtCore.QRect(290, 310, 141, 27))
        self.dateAdded.setInputMethodHints(QtCore.Qt.ImhNone)
        self.dateAdded.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dateAdded.setMinimumDate(QtCore.QDate(2018, 6, 20))
        self.dateAdded.setCalendarPopup(True)
        self.dateAdded.setObjectName("dateAdded")
        self.salePrice = QtWidgets.QLineEdit(FormProduct)
        self.salePrice.setGeometry(QtCore.QRect(120, 260, 301, 27))
        self.salePrice.setObjectName("salePrice")
        self.btnAddSupplier = QtWidgets.QPushButton(FormProduct)
        self.btnAddSupplier.setGeometry(QtCore.QRect(360, 360, 41, 27))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnAddSupplier.setFont(font)
        self.btnAddSupplier.setStyleSheet("color:#f64")
        self.btnAddSupplier.setAutoDefault(True)
        self.btnAddSupplier.setDefault(False)
        self.btnAddSupplier.setObjectName("btnAddSupplier")
        self.quantity = QtWidgets.QLineEdit(FormProduct)
        self.quantity.setGeometry(QtCore.QRect(90, 160, 121, 27))
        self.quantity.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.quantity.setObjectName("quantity")
        self.lblQuantity = QtWidgets.QLabel(FormProduct)
        self.lblQuantity.setGeometry(QtCore.QRect(20, 160, 64, 27))
        self.lblQuantity.setObjectName("lblQuantity")
        self.lblSupplier = QtWidgets.QLabel(FormProduct)
        self.lblSupplier.setGeometry(QtCore.QRect(20, 360, 61, 27))
        self.lblSupplier.setObjectName("lblSupplier")
        self.lblDate = QtWidgets.QLabel(FormProduct)
        self.lblDate.setGeometry(QtCore.QRect(240, 310, 41, 27))
        self.lblDate.setObjectName("lblDate")
        self.realPrice = QtWidgets.QLineEdit(FormProduct)
        self.realPrice.setGeometry(QtCore.QRect(120, 210, 311, 27))
        self.realPrice.setObjectName("realPrice")
        self.productCode = QtWidgets.QLineEdit(FormProduct)
        self.productCode.setGeometry(QtCore.QRect(130, 110, 301, 27))
        self.productCode.setObjectName("productCode")
        self.lblRealPrice = QtWidgets.QLabel(FormProduct)
        self.lblRealPrice.setGeometry(QtCore.QRect(20, 210, 92, 27))
        self.lblRealPrice.setToolTip("")
        self.lblRealPrice.setProperty("toolTipDuration", 2)
        self.lblRealPrice.setObjectName("lblRealPrice")
        self.btnCancel = QtWidgets.QPushButton(FormProduct)
        self.btnCancel.setGeometry(QtCore.QRect(60, 410, 99, 31))
        self.btnCancel.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnCancel.setObjectName("btnCancel")
        self.supplier = QtWidgets.QComboBox(FormProduct)
        self.supplier.setGeometry(QtCore.QRect(94, 360, 261, 27))
        self.supplier.setObjectName("supplier")
        self.label = QtWidgets.QLabel(FormProduct)
        self.label.setGeometry(QtCore.QRect(0, 0, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblProductName = QtWidgets.QLabel(FormProduct)
        self.lblProductName.setGeometry(QtCore.QRect(20, 60, 102, 27))
        self.lblProductName.setObjectName("lblProductName")
        self.total = QtWidgets.QLineEdit(FormProduct)
        self.total.setGeometry(QtCore.QRect(60, 310, 171, 27))
        self.total.setObjectName("total")
        self.lblSalePrice = QtWidgets.QLabel(FormProduct)
        self.lblSalePrice.setGeometry(QtCore.QRect(20, 260, 81, 27))
        self.lblSalePrice.setObjectName("lblSalePrice")
        self.label_2 = QtWidgets.QLabel(FormProduct)
        self.label_2.setGeometry(QtCore.QRect(230, 164, 68, 17))
        self.label_2.setObjectName("label_2")
        self.category = QtWidgets.QComboBox(FormProduct)
        self.category.setGeometry(QtCore.QRect(300, 160, 131, 27))
        self.category.setObjectName("category")

        self.retranslateUi(FormProduct)
        QtCore.QMetaObject.connectSlotsByName(FormProduct)

    def retranslateUi(self, FormProduct):
        _translate = QtCore.QCoreApplication.translate
        FormProduct.setWindowTitle(_translate("FormProduct", "Add a new product"))
        self.btnSave.setText(_translate("FormProduct", "Save"))
        self.lblTotal.setText(_translate("FormProduct", "Total:"))
        self.lblProductCode.setText(_translate("FormProduct", "Produc Code:"))
        self.btnAddSupplier.setToolTip(_translate("FormProduct", "Add new supplier"))
        self.btnAddSupplier.setText(_translate("FormProduct", "+"))
        self.lblQuantity.setText(_translate("FormProduct", "Quantity:"))
        self.lblSupplier.setText(_translate("FormProduct", "Supplier:"))
        self.lblDate.setText(_translate("FormProduct", "Date:"))
        self.lblRealPrice.setText(_translate("FormProduct", "Real Price:"))
        self.btnCancel.setText(_translate("FormProduct", "Cancel"))
        self.label.setText(_translate("FormProduct", "New Product"))
        self.lblProductName.setText(_translate("FormProduct", "Product Name:"))
        self.lblSalePrice.setText(_translate("FormProduct", "Sale Price:"))
        self.label_2.setText(_translate("FormProduct", "Category:"))
        self.day = strftime("%y%m%d%H%M%S", gmtime())
        self.prefix = "10"
        self.productCode.setText(self.prefix + self.day)
        self.productCode.setDisabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormProduct = QtWidgets.QDialog()
    ui = Ui_FormProduct()
    ui.setupUi(FormProduct)
    FormProduct.show()
    sys.exit(app.exec_())

