# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/invoice.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newInvoice(object):
    def setupUi(self, newInvoice):
        newInvoice.setObjectName("newInvoice")
        newInvoice.resize(758, 654)
        self.centralwidget = QtWidgets.QWidget(newInvoice)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -38, 1031, 745))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.printContainer = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.printContainer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0;\n"
"margin:10px 5px 12px 5px;")
        self.printContainer.setTitle("")
        self.printContainer.setObjectName("printContainer")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.printContainer)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_2 = QtWidgets.QFrame(self.printContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setMinimumSize(QtCore.QSize(0, 3))
        self.line_2.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 9, 0, 1, 8)
        self.balance = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.balance.setFont(font)
        self.balance.setText("")
        self.balance.setObjectName("balance")
        self.gridLayout_4.addWidget(self.balance, 7, 3, 1, 5)
        self.companyLabel = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.companyLabel.setFont(font)
        self.companyLabel.setStyleSheet("color: rgb(0, 85, 255);")
        self.companyLabel.setObjectName("companyLabel")
        self.gridLayout_4.addWidget(self.companyLabel, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.printContainer)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 1, 2, 2)
        self.toName = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.toName.setFont(font)
        self.toName.setStyleSheet("color: rgb(0, 85, 0);")
        self.toName.setText("")
        self.toName.setObjectName("toName")
        self.gridLayout_4.addWidget(self.toName, 3, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.invoiceNo = QtWidgets.QLabel(self.printContainer)
        self.invoiceNo.setStyleSheet("")
        self.invoiceNo.setText("")
        self.invoiceNo.setObjectName("invoiceNo")
        self.gridLayout_4.addWidget(self.invoiceNo, 0, 5, 1, 3)
        self.label = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 85, 0);\n"
"padding: 0px;")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 3)
        self.amountPaid = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.amountPaid.setFont(font)
        self.amountPaid.setText("")
        self.amountPaid.setObjectName("amountPaid")
        self.gridLayout_4.addWidget(self.amountPaid, 15, 2, 1, 5)
        self.label_5 = QtWidgets.QLabel(self.printContainer)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.printContainer)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 12, 1, 1, 1)
        self.paymentStatus = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paymentStatus.setFont(font)
        self.paymentStatus.setText("")
        self.paymentStatus.setObjectName("paymentStatus")
        self.gridLayout_4.addWidget(self.paymentStatus, 4, 3, 1, 5)
        self.label_11 = QtWidgets.QLabel(self.printContainer)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 15, 1, 1, 1)
        self.date = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.date.setFont(font)
        self.date.setText("")
        self.date.setObjectName("date")
        self.gridLayout_4.addWidget(self.date, 2, 3, 1, 5)
        self.dueDate = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dueDate.setFont(font)
        self.dueDate.setText("")
        self.dueDate.setObjectName("dueDate")
        self.gridLayout_4.addWidget(self.dueDate, 5, 3, 1, 5)
        self.line = QtWidgets.QFrame(self.printContainer)
        self.line.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 8)
        self.label_9 = QtWidgets.QLabel(self.printContainer)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 13, 1, 1, 1)
        self.tax = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tax.setFont(font)
        self.tax.setText("")
        self.tax.setObjectName("tax")
        self.gridLayout_4.addWidget(self.tax, 13, 2, 1, 5)
        self.invoiceView = QtWidgets.QTableView(self.printContainer)
        self.invoiceView.setMinimumSize(QtCore.QSize(985, 223))
        self.invoiceView.setAlternatingRowColors(True)
        self.invoiceView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.invoiceView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.invoiceView.setSortingEnabled(True)
        self.invoiceView.setObjectName("invoiceView")
        self.invoiceView.horizontalHeader().setCascadingSectionResizes(True)
        self.invoiceView.horizontalHeader().setDefaultSectionSize(130)
        self.invoiceView.horizontalHeader().setMinimumSectionSize(100)
        self.invoiceView.horizontalHeader().setSortIndicatorShown(True)
        self.invoiceView.verticalHeader().setDefaultSectionSize(35)
        self.invoiceView.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout_4.addWidget(self.invoiceView, 10, 0, 1, 8)
        self.label_6 = QtWidgets.QLabel(self.printContainer)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.printContainer)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 1, 1, 1)
        self.total = QtWidgets.QLabel(self.printContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.total.setFont(font)
        self.total.setText("")
        self.total.setObjectName("total")
        self.gridLayout_4.addWidget(self.total, 14, 2, 1, 5)
        self.label_10 = QtWidgets.QLabel(self.printContainer)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 14, 1, 1, 1)
        self.subtotal = QtWidgets.QLabel(self.printContainer)
        self.subtotal.setText("")
        self.subtotal.setObjectName("subtotal")
        self.gridLayout_4.addWidget(self.subtotal, 12, 2, 1, 5)
        self.line_3 = QtWidgets.QFrame(self.printContainer)
        self.line_3.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 11, 0, 1, 8)
        self.gridLayout_3.addWidget(self.printContainer, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(30, 10, 30, 10)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnPrint = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.btnPrint.setStyleSheet("padding:12px;")
        self.btnPrint.setObjectName("btnPrint")
        self.horizontalLayout_2.addWidget(self.btnPrint)
        self.btnEmail = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.btnEmail.setStyleSheet("padding:12px;")
        self.btnEmail.setObjectName("btnEmail")
        self.horizontalLayout_2.addWidget(self.btnEmail)
        self.btnCancel = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.btnCancel.setStyleSheet("padding:12px;")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.gridLayout.addWidget(self.horizontalGroupBox, 1, 0, 1, 1)
        newInvoice.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(newInvoice)
        self.statusbar.setObjectName("statusbar")
        newInvoice.setStatusBar(self.statusbar)

        self.retranslateUi(newInvoice)
        self.btnCancel.clicked.connect(newInvoice.close)
        QtCore.QMetaObject.connectSlotsByName(newInvoice)

    def retranslateUi(self, newInvoice):
        _translate = QtCore.QCoreApplication.translate
        newInvoice.setWindowTitle(_translate("newInvoice", "New Invoice"))
        self.companyLabel.setText(_translate("newInvoice", "Ahasaniya Enterprise"))
        self.label_4.setText(_translate("newInvoice", "Payment Status:"))
        self.label_3.setText(_translate("newInvoice", "Billed To:"))
        self.label.setText(_translate("newInvoice", "Invoice No:"))
        self.label_5.setText(_translate("newInvoice", "Due Date:"))
        self.label_7.setText(_translate("newInvoice", "Subtotal:"))
        self.label_11.setText(_translate("newInvoice", "Amount Paid:"))
        self.label_9.setText(_translate("newInvoice", "Tax:"))
        self.label_6.setText(_translate("newInvoice", "Balance:"))
        self.label_2.setText(_translate("newInvoice", "Date:"))
        self.label_10.setText(_translate("newInvoice", "Total:"))
        self.btnPrint.setText(_translate("newInvoice", "Print Invoice"))
        self.btnEmail.setText(_translate("newInvoice", "Send as Email"))
        self.btnCancel.setText(_translate("newInvoice", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newInvoice = QtWidgets.QMainWindow()
    ui = Ui_newInvoice()
    ui.setupUi(newInvoice)
    newInvoice.show()
    sys.exit(app.exec_())

