# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 608)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralWidget.setObjectName("centralWidget")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 874, 25))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuExport = QtWidgets.QMenu(self.menuTools)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menuTools)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Product = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/Product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Product.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionNew_Product.setFont(font)
        self.actionNew_Product.setObjectName("actionNew_Product")
        self.actionNew_Category = QtWidgets.QAction(MainWindow)
        self.actionNew_Category.setObjectName("actionNew_Category")
        self.actionNew_Invoice = QtWidgets.QAction(MainWindow)
        self.actionNew_Invoice.setObjectName("actionNew_Invoice")
        self.actionCompany_Info = QtWidgets.QAction(MainWindow)
        self.actionCompany_Info.setObjectName("actionCompany_Info")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.actionCustomer_Info = QtWidgets.QAction(MainWindow)
        self.actionCustomer_Info.setObjectName("actionCustomer_Info")
        self.actionCreditors = QtWidgets.QAction(MainWindow)
        self.actionCreditors.setObjectName("actionCreditors")
        self.actionDebtors = QtWidgets.QAction(MainWindow)
        self.actionDebtors.setObjectName("actionDebtors")
        self.actionProducts = QtWidgets.QAction(MainWindow)
        self.actionProducts.setObjectName("actionProducts")
        self.actionProduct_Categories = QtWidgets.QAction(MainWindow)
        self.actionProduct_Categories.setObjectName("actionProduct_Categories")
        self.actionInvoices = QtWidgets.QAction(MainWindow)
        self.actionInvoices.setObjectName("actionInvoices")
        self.actionCompany_Info_2 = QtWidgets.QAction(MainWindow)
        self.actionCompany_Info_2.setObjectName("actionCompany_Info_2")
        self.actionCustomers = QtWidgets.QAction(MainWindow)
        self.actionCustomers.setObjectName("actionCustomers")
        self.actionContacts = QtWidgets.QAction(MainWindow)
        self.actionContacts.setObjectName("actionContacts")
        self.actionAll_Products = QtWidgets.QAction(MainWindow)
        self.actionAll_Products.setObjectName("actionAll_Products")
        self.actionProducts_2 = QtWidgets.QAction(MainWindow)
        self.actionProducts_2.setObjectName("actionProducts_2")
        self.actionCustomer_Info_2 = QtWidgets.QAction(MainWindow)
        self.actionCustomer_Info_2.setObjectName("actionCustomer_Info_2")
        self.actionCompany_Info_3 = QtWidgets.QAction(MainWindow)
        self.actionCompany_Info_3.setObjectName("actionCompany_Info_3")
        self.actionContact_2 = QtWidgets.QAction(MainWindow)
        self.actionContact_2.setObjectName("actionContact_2")
        self.actionCategories = QtWidgets.QAction(MainWindow)
        self.actionCategories.setObjectName("actionCategories")
        self.actionLogs = QtWidgets.QAction(MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionProduct_Support = QtWidgets.QAction(MainWindow)
        self.actionProduct_Support.setObjectName("actionProduct_Support")
        self.actionAbout_IMS = QtWidgets.QAction(MainWindow)
        self.actionAbout_IMS.setObjectName("actionAbout_IMS")
        self.actionReport_Bugs = QtWidgets.QAction(MainWindow)
        self.actionReport_Bugs.setObjectName("actionReport_Bugs")
        self.actionBackup_Data = QtWidgets.QAction(MainWindow)
        self.actionBackup_Data.setObjectName("actionBackup_Data")
        self.actionExcel = QtWidgets.QAction(MainWindow)
        self.actionExcel.setObjectName("actionExcel")
        self.actionCSV = QtWidgets.QAction(MainWindow)
        self.actionCSV.setObjectName("actionCSV")
        self.actionBulk_Email = QtWidgets.QAction(MainWindow)
        self.actionBulk_Email.setObjectName("actionBulk_Email")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExcel_File = QtWidgets.QAction(MainWindow)
        self.actionExcel_File.setObjectName("actionExcel_File")
        self.actionCSV_2 = QtWidgets.QAction(MainWindow)
        self.actionCSV_2.setObjectName("actionCSV_2")
        self.actionODF_Spreadsheet = QtWidgets.QAction(MainWindow)
        self.actionODF_Spreadsheet.setObjectName("actionODF_Spreadsheet")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionStaff = QtWidgets.QAction(MainWindow)
        self.actionStaff.setObjectName("actionStaff")
        self.actionStaff_2 = QtWidgets.QAction(MainWindow)
        self.actionStaff_2.setObjectName("actionStaff_2")
        self.actionStore_Statistics = QtWidgets.QAction(MainWindow)
        self.actionStore_Statistics.setObjectName("actionStore_Statistics")
        self.menuFile.addAction(self.actionNew_Product)
        self.menuFile.addAction(self.actionNew_Category)
        self.menuFile.addAction(self.actionNew_Invoice)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCompany_Info)
        self.menuFile.addAction(self.actionCustomer_Info)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionContact)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStaff)
        self.menuView.addAction(self.actionCreditors)
        self.menuView.addAction(self.actionDebtors)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionProducts)
        self.menuView.addAction(self.actionProduct_Categories)
        self.menuView.addAction(self.actionAll_Products)
        self.menuView.addAction(self.actionInvoices)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionCompany_Info_2)
        self.menuView.addAction(self.actionCustomers)
        self.menuView.addAction(self.actionContacts)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStaff_2)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionLogs)
        self.menuView.addAction(self.actionStore_Statistics)
        self.menuEdit.addAction(self.actionProducts_2)
        self.menuEdit.addAction(self.actionCustomer_Info_2)
        self.menuEdit.addAction(self.actionCompany_Info_3)
        self.menuEdit.addAction(self.actionContact_2)
        self.menuEdit.addAction(self.actionCategories)
        self.menuEdit.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionProduct_Support)
        self.menuHelp.addAction(self.actionAbout_IMS)
        self.menuHelp.addAction(self.actionReport_Bugs)
        self.menuExport.addAction(self.actionExcel)
        self.menuExport.addAction(self.actionCSV)
        self.menuImport.addAction(self.actionExcel_File)
        self.menuImport.addAction(self.actionCSV_2)
        self.menuImport.addAction(self.actionODF_Spreadsheet)
        self.menuTools.addAction(self.actionBackup_Data)
        self.menuTools.addAction(self.menuExport.menuAction())
        self.menuTools.addAction(self.menuImport.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionBulk_Email)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPrint)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionOptions)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "Create"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.actionNew_Product.setText(_translate("MainWindow", "New Product"))
        self.actionNew_Product.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionNew_Category.setText(_translate("MainWindow", "New Category"))
        self.actionNew_Category.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionNew_Invoice.setText(_translate("MainWindow", "New Invoice"))
        self.actionNew_Invoice.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionCompany_Info.setText(_translate("MainWindow", "Company Info"))
        self.actionCompany_Info.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionContact.setText(_translate("MainWindow", "Contact"))
        self.actionContact.setShortcut(_translate("MainWindow", "Alt+N"))
        self.actionCustomer_Info.setText(_translate("MainWindow", "Customer Info"))
        self.actionCustomer_Info.setShortcut(_translate("MainWindow", "Ctrl+Alt+N"))
        self.actionCreditors.setText(_translate("MainWindow", "Creditors"))
        self.actionDebtors.setText(_translate("MainWindow", "Debtors"))
        self.actionProducts.setText(_translate("MainWindow", "Product Inventory"))
        self.actionProduct_Categories.setText(_translate("MainWindow", "Product Categories"))
        self.actionInvoices.setText(_translate("MainWindow", "Invoices"))
        self.actionCompany_Info_2.setText(_translate("MainWindow", "Company Info"))
        self.actionCustomers.setText(_translate("MainWindow", "Customers"))
        self.actionContacts.setText(_translate("MainWindow", "Contacts"))
        self.actionAll_Products.setText(_translate("MainWindow", "All Products"))
        self.actionProducts_2.setText(_translate("MainWindow", "Products"))
        self.actionCustomer_Info_2.setText(_translate("MainWindow", "Customer Info"))
        self.actionCompany_Info_3.setText(_translate("MainWindow", "Company Info"))
        self.actionContact_2.setText(_translate("MainWindow", "Contact"))
        self.actionCategories.setText(_translate("MainWindow", "Categories"))
        self.actionLogs.setText(_translate("MainWindow", "Logs"))
        self.actionHelp.setText(_translate("MainWindow", "Help Content"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionProduct_Support.setText(_translate("MainWindow", "Product Support"))
        self.actionProduct_Support.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.actionAbout_IMS.setText(_translate("MainWindow", "About IMS"))
        self.actionReport_Bugs.setText(_translate("MainWindow", "Report Bugs"))
        self.actionBackup_Data.setText(_translate("MainWindow", "Backup Data"))
        self.actionExcel.setText(_translate("MainWindow", "Excel"))
        self.actionCSV.setText(_translate("MainWindow", "CSV"))
        self.actionBulk_Email.setText(_translate("MainWindow", "Bulk Email"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionExcel_File.setText(_translate("MainWindow", "Excel File"))
        self.actionCSV_2.setText(_translate("MainWindow", "CSV File"))
        self.actionODF_Spreadsheet.setText(_translate("MainWindow", "ODF Spreadsheet"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionStaff.setText(_translate("MainWindow", "New Employee"))
        self.actionStaff_2.setText(_translate("MainWindow", "Staff"))
        self.actionStore_Statistics.setText(_translate("MainWindow", "Store Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

