# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/newinvoice.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import sql
import sqlite3
from functions import num_rows
from time import strftime, gmtime

class Ui_NewInvoice(object):
    def setupUi(self, NewInvoice):
        NewInvoice.setObjectName("NewInvoice")
        NewInvoice.resize(772, 618)
        NewInvoice.setMinimumSize(QtCore.QSize(772, 0))
        NewInvoice.setMaximumSize(QtCore.QSize(772, 16777215))
        self.centralwidget = QtWidgets.QWidget(NewInvoice)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setStyleSheet("max-width:100px;\n"
"min-height:25px;")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnSubmit = QtWidgets.QPushButton(self.centralwidget)
        self.btnSubmit.setStyleSheet("max-width:100px;\n"
"min-height:25px;")
        self.btnSubmit.setObjectName("btnSubmit")
        self.horizontalLayout.addWidget(self.btnSubmit)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setStyleSheet("max-width:120px;\n"
"min-height:25px;")
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("min-height:50px;\n"
"font: 63 bold 16pt \"Arial\";")
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.name_enter = QtWidgets.QLineEdit(self.groupBox)
        self.name_enter.setStyleSheet("min-width:200px;\n"
"min-height:25px;")
        self.name_enter.setObjectName("name_enter")
        self.gridLayout_4.addWidget(self.name_enter, 4, 0, 1, 1)
        self.customer = QtWidgets.QComboBox(self.groupBox)
        self.customer.setStyleSheet("min-width:200px;\n"
"min-height:25px;")
        self.customer.setObjectName("customer")
        self.gridLayout_4.addWidget(self.customer, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.invoice_no = QtWidgets.QLineEdit(self.groupBox)
        self.invoice_no.setEnabled(False)
        self.invoice_no.setObjectName("inovice_no")
        self.gridLayout_4.addWidget(self.invoice_no, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setStyleSheet("min-width:180px;")
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.quantity = QtWidgets.QLineEdit(self.groupBox1)
        self.quantity.setStyleSheet("min-width:200px;\n"
"min-height:25px;")
        self.quantity.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.quantity, 2, 2, 1, 2)
        self.status = QtWidgets.QComboBox(self.groupBox1)
        self.status.setStyleSheet("min-width:200px;\n"
"min-height:25px;")
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.gridLayout.addWidget(self.status, 3, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.select_product = QtWidgets.QComboBox(self.groupBox1)
        self.select_product.setStyleSheet("min-width:200px;\n"
"min-height:25px;")
        self.select_product.setObjectName("select_product")
        self.gridLayout.addWidget(self.select_product, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.amount = QtWidgets.QLineEdit(self.groupBox1)
        self.amount.setStyleSheet("min-width:200px;\n"
"min-height:25px;")
        self.amount.setObjectName("amount")
        self.gridLayout.addWidget(self.amount, 1, 2, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 2)
        self.productsView = QtWidgets.QTableView(self.centralwidget)
        self.productsView.setStyleSheet("max-height:350px;")
        self.productsView.setObjectName("productsView")
        self.gridLayout_3.addWidget(self.productsView, 3, 0, 1, 1)
        NewInvoice.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewInvoice)
        self.btnCancel.clicked.connect(NewInvoice.close)
        self.fill_model()
        QtCore.QMetaObject.connectSlotsByName(NewInvoice)

    def retranslateUi(self, NewInvoice):
        _translate = QtCore.QCoreApplication.translate
        NewInvoice.setWindowTitle(_translate("NewInvoice", "Add Invoices to Generate"))
        self.btnCancel.setText(_translate("NewInvoice", "Cancel"))
        self.btnSubmit.setText(_translate("NewInvoice", "Generate"))
        self.btnAdd.setText(_translate("NewInvoice", "+ Add Product"))
        self.label_8.setText(_translate("NewInvoice", "Items Added:"))
        self.groupBox.setTitle(_translate("NewInvoice", "Customer details"))
        self.label_3.setText(_translate("NewInvoice", "Customer:"))
        self.label_6.setText(_translate("NewInvoice", "Or"))
        self.label_7.setText(_translate("NewInvoice", "Enter Customer Name:"))
        self.groupBox1.setTitle(_translate("NewInvoice", "Sales & Product Details"))
        self.label_2.setText(_translate("NewInvoice", "Status:"))
        self.status.setItemText(0, _translate("NewInvoice", "Paid"))
        self.status.setItemText(1, _translate("NewInvoice", "Pending Payment"))
        self.status.setItemText(2, _translate("NewInvoice", "Unpaid"))
        self.label_5.setText(_translate("NewInvoice", "Quantity:"))
        self.label.setText(_translate("NewInvoice", "Select Product:"))
        self.label_4.setText(_translate("NewInvoice", "Amount:"))


    def fill_model(self):
        if sql.connectDB():
            mod = QtSql.QSqlQueryModel()
            querry = QtSql.QSqlQuery()
            querry.exec_("select distinct name from customers")
            mod.setQuery(querry)
            print(mod.rowCount())
            complet = QtWidgets.QCompleter()
            complet.setFilterMode(QtCore.Qt.MatchContains)
            complet.setCaseSensitivity(QtCore.Qt.CaseInsensitive)
            complet.setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
            self.name_enter.setCompleter(complet)
            complet.setModel(mod)
            self.name_enter.setFocus(QtCore.Qt.PopupFocusReason)
            if mod.rowCount() > 0:
                self.customer.setModel(mod)
            model = QtSql.QSqlQueryModel()
            query = QtSql.QSqlQuery()
            query.exec_("Select distinct product_name from products")
            model.setQuery(query)
            if num_rows(query) > 0:
                self.select_product.setModel(model)
            qury = QtSql.QSqlQuery()
            modal = QtSql.QSqlQueryModel()
            qury.exec_("select * from invoices where invoice_number = ? and customer_name = ? and date_bought = ?")
            qury.bindValue(0, self.invoice_no.text())
            qury.bindValue(1, self.customer.currentText())
            qury.bindValue(2,strftime("%d/%m/Y", gmtime()))
            qury.exec_()
            modal.setHeaderData(1, QtCore.Qt.Horizontal, "Customer Name")
            modal.setHeaderData(2, QtCore.Qt.Horizontal, "Invoice No")
            modal.setHeaderData(3, QtCore.Qt.Horizontal, "Product Code")
            modal.setHeaderData(4, QtCore.Qt.Horizontal, "Product Name")
            modal.setHeaderData(5, QtCore.Qt.Horizontal, "Price")
            modal.setHeaderData(6, QtCore.Qt.Horizontal, "Real Price")
            modal.setHeaderData(7, QtCore.Qt.Horizontal, "Amount")
            modal.setHeaderData(8, QtCore.Qt.Horizontal, "Balance")
            modal.setHeaderData(8, QtCore.Qt.Horizontal, "Quantity")
            modal.setHeaderData(10, QtCore.Qt.Horizontal, "Total")
            modal.setHeaderData(11, QtCore.Qt.Horizontal, "Date")
            self.productsView.setModel(modal)
            self.productsView.horizontalHeader().setMinimumHeight(40)
            self.productsView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
            self.productsView.setShowGrid(True)
            self.productsView.show()

