# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'products.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import sql

class Ui_frmProductsLists(object):
    def setupUi(self, frmProductsLists):
        frmProductsLists.setObjectName("frmProductsLists")
        frmProductsLists.resize(1205, 565)
        self.buttonBox = QtWidgets.QDialogButtonBox(frmProductsLists)
        self.buttonBox.setGeometry(QtCore.QRect(830, 520, 341, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox_2 = QtWidgets.QGroupBox(frmProductsLists)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 20, 421, 80))
        self.groupBox_2.setStyleSheet("background-color: rgb(255,255,255);\n"
"border:1px solid #999;\n"
"border-radius: 4px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.supplier_filter = QtWidgets.QLineEdit(self.groupBox_2)
        self.supplier_filter.setGeometry(QtCore.QRect(20, 40, 271, 25))
        self.supplier_filter.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.supplier_filter.setObjectName("supplier_filter")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 191, 21))
        self.label_7.setStyleSheet("border:0;")
        self.label_7.setObjectName("label_7")
        self.btnSearch = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSearch.setGeometry(QtCore.QRect(300, 40, 99, 27))
        self.btnSearch.setObjectName("btnSearch")
        self.tableView = QtWidgets.QTableView(frmProductsLists)
        self.tableView.setGeometry(QtCore.QRect(30, 120, 1141, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableView.setLineWidth(1)
        self.tableView.setMidLineWidth(0)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setIconSize(QtCore.QSize(0, 0))
        self.tableView.setShowGrid(False)
        self.tableView.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(150)
        self.groupBox_3 = QtWidgets.QGroupBox(frmProductsLists)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 20, 711, 80))
        self.groupBox_3.setStyleSheet("background-color: rgb(255,255,255);\n"
"border:1px solid #999;\n"
"border-radius: 4px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnReset = QtWidgets.QPushButton(self.groupBox_3)
        self.btnReset.setGeometry(QtCore.QRect(30, 20, 111, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnReset.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnReset.setFont(font)
        self.btnReset.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/Reset2_32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReset.setIcon(icon)
        self.btnReset.setIconSize(QtCore.QSize(25, 25))
        self.btnReset.setAutoDefault(False)
        self.btnReset.setObjectName("btnReset")
        self.btnExport = QtWidgets.QPushButton(self.groupBox_3)
        self.btnExport.setGeometry(QtCore.QRect(160, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnExport.setFont(font)
        self.btnExport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnExport.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/Excel-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExport.setIcon(icon1)
        self.btnExport.setIconSize(QtCore.QSize(25, 25))
        self.btnExport.setAutoDefault(False)
        self.btnExport.setObjectName("btnExport")
        self.btnDelete = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDelete.setGeometry(QtCore.QRect(310, 20, 121, 41))
        self.btnDelete.setObjectName("btnDelete")
        self.btnEdit = QtWidgets.QPushButton(self.groupBox_3)
        self.btnEdit.setGeometry(QtCore.QRect(450, 19, 111, 41))
        self.btnEdit.setObjectName("btnEdit")
        self.btnDeleteAll = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDeleteAll.setGeometry(QtCore.QRect(580, 18, 99, 41))
        self.btnDeleteAll.setObjectName("btnDeleteAll")

        self.retranslateUi(frmProductsLists)
        self.buttonBox.accepted.connect(frmProductsLists.accept)
        self.buttonBox.rejected.connect(frmProductsLists.reject)
        QtCore.QMetaObject.connectSlotsByName(frmProductsLists)

    def retranslateUi(self, frmProductsLists):
        _translate = QtCore.QCoreApplication.translate
        frmProductsLists.setWindowTitle(_translate("frmProductsLists", "Products"))
        self.label_7.setText(_translate("frmProductsLists", "Search by supplier name:"))
        self.btnSearch.setText(_translate("frmProductsLists", "Search"))
        self.btnReset.setText(_translate("frmProductsLists", "Reset"))
        self.btnExport.setText(_translate("frmProductsLists", "Export excel"))
        self.btnDelete.setText(_translate("frmProductsLists", "Delete Seleted"))
        self.btnEdit.setText(_translate("frmProductsLists", "Edit Selected"))
        self.btnDeleteAll.setText(_translate("frmProductsLists", "Delete All"))

    def selectProducts(self):
        sql.connectDB()
        model = QtSql.QSqlTableModel()
        q = QtSql.QSqlQuery()
        model.setTable("products")
        model.setEditStrategy(QtSql.QSqlTableModel.OnManualSubmit)
        model.setHeaderData(0, QtCore.Qt.Horizontal, "ID")
        model.setHeaderData(1, QtCore.Qt.Horizontal, "Product Code")
        model.setHeaderData(2, QtCore.Qt.Horizontal, "Product Name")
        model.setHeaderData(3, QtCore.Qt.Horizontal, "Product Price")
        model.setHeaderData(4, QtCore.Qt.Horizontal, "Sale Price")
        model.setHeaderData(5, QtCore.Qt.Horizontal, "Total Price")
        model.setHeaderData(6, QtCore.Qt.Horizontal, "Quantity")
        model.setHeaderData(7, QtCore.Qt.Horizontal, "Category")
        model.setHeaderData(8, QtCore.Qt.Horizontal, "Date Added")
        model.setHeaderData(9, QtCore.Qt.Horizontal, "Supplier")
        model.select()
        self.tableView.setModel(model)
        self.tableView.horizontalHeader().setMinimumHeight(40)
        self.tableView.horizontalHeader().setStyleSheet("background-color:#111;color:#dadada")
        self.tableView.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableView.setShowGrid(True)
        self.tableView.show()
    #
    # def reset(self):
    #     row = self.tableView.

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmProductsLists = QtWidgets.QDialog()
    frmProductsLists.setWindowTitle("Products")
    ui = Ui_frmProductsLists()
    ui.setupUi(frmProductsLists)
    ui.selectProducts()
    ui.tableView.setColumnHidden(0, True)
    frmProductsLists.setGeometry(40, 20, 1280, 650)
    frmProductsLists.show()
    sys.exit(app.exec_())

