# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplier.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Supplier(object):
    def setupUi(self, Supplier):
        Supplier.setObjectName("Supplier")
        Supplier.resize(621, 583)
        self.centralWidget = QtWidgets.QWidget(Supplier)
        self.centralWidget.setObjectName("centralWidget")
        self.groupSupplier = QtWidgets.QGroupBox(self.centralWidget)
        self.groupSupplier.setGeometry(QtCore.QRect(10, 40, 601, 461))
        self.groupSupplier.setStyleSheet("border:1px solid #ccc;")
        self.groupSupplier.setTitle("")
        self.groupSupplier.setObjectName("groupSupplier")
        self.label = QtWidgets.QLabel(self.groupSupplier)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 17))
        self.label.setStyleSheet("border:0;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupSupplier)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 61, 17))
        self.label_2.setStyleSheet("border:0;")
        self.label_2.setObjectName("label_2")
        self.contact = QtWidgets.QLineEdit(self.groupSupplier)
        self.contact.setGeometry(QtCore.QRect(370, 16, 211, 28))
        self.contact.setObjectName("contact")
        self.label_3 = QtWidgets.QLabel(self.groupSupplier)
        self.label_3.setGeometry(QtCore.QRect(20, 74, 41, 17))
        self.label_3.setStyleSheet("border:0;")
        self.label_3.setObjectName("label_3")
        self.city = QtWidgets.QLineEdit(self.groupSupplier)
        self.city.setGeometry(QtCore.QRect(60, 70, 181, 27))
        self.city.setObjectName("city")
        self.label_4 = QtWidgets.QLabel(self.groupSupplier)
        self.label_4.setGeometry(QtCore.QRect(250, 74, 51, 17))
        self.label_4.setStyleSheet("border:0;")
        self.label_4.setObjectName("label_4")
        self.region = QtWidgets.QLineEdit(self.groupSupplier)
        self.region.setGeometry(QtCore.QRect(310, 70, 271, 27))
        self.region.setObjectName("region")
        self.label_5 = QtWidgets.QLabel(self.groupSupplier)
        self.label_5.setGeometry(QtCore.QRect(20, 136, 31, 17))
        self.label_5.setStyleSheet("border:0;")
        self.label_5.setObjectName("label_5")
        self.fax = QtWidgets.QLineEdit(self.groupSupplier)
        self.fax.setGeometry(QtCore.QRect(60, 130, 241, 27))
        self.fax.setObjectName("fax")
        self.label_6 = QtWidgets.QLabel(self.groupSupplier)
        self.label_6.setGeometry(QtCore.QRect(330, 126, 67, 17))
        self.label_6.setStyleSheet("border:0;")
        self.label_6.setObjectName("label_6")
        self.address = QtWidgets.QTextEdit(self.groupSupplier)
        self.address.setGeometry(QtCore.QRect(330, 147, 251, 71))
        self.address.setObjectName("address")
        self.label_7 = QtWidgets.QLabel(self.groupSupplier)
        self.label_7.setGeometry(QtCore.QRect(20, 194, 111, 17))
        self.label_7.setStyleSheet("border:0;")
        self.label_7.setObjectName("label_7")
        self.postalAddress = QtWidgets.QLineEdit(self.groupSupplier)
        self.postalAddress.setGeometry(QtCore.QRect(130, 190, 191, 27))
        self.postalAddress.setObjectName("postalAddress")
        self.label_8 = QtWidgets.QLabel(self.groupSupplier)
        self.label_8.setGeometry(QtCore.QRect(20, 250, 151, 17))
        self.label_8.setStyleSheet("border:0;")
        self.label_8.setObjectName("label_8")
        self.registrationNumber = QtWidgets.QLineEdit(self.groupSupplier)
        self.registrationNumber.setGeometry(QtCore.QRect(180, 246, 401, 27))
        self.registrationNumber.setObjectName("registrationNumber")
        self.label_9 = QtWidgets.QLabel(self.groupSupplier)
        self.label_9.setGeometry(QtCore.QRect(20, 310, 67, 17))
        self.label_9.setStyleSheet("border:0;")
        self.label_9.setObjectName("label_9")
        self.email = QtWidgets.QLineEdit(self.groupSupplier)
        self.email.setGeometry(QtCore.QRect(70, 305, 191, 27))
        self.email.setObjectName("email")
        self.label_10 = QtWidgets.QLabel(self.groupSupplier)
        self.label_10.setGeometry(QtCore.QRect(280, 310, 121, 17))
        self.label_10.setStyleSheet("border:0;")
        self.label_10.setObjectName("label_10")
        self.productsInStore = QtWidgets.QLineEdit(self.groupSupplier)
        self.productsInStore.setGeometry(QtCore.QRect(410, 305, 171, 27))
        self.productsInStore.setObjectName("productsInStore")
        self.label_11 = QtWidgets.QLabel(self.groupSupplier)
        self.label_11.setGeometry(QtCore.QRect(20, 350, 231, 17))
        self.label_11.setStyleSheet("border:0;")
        self.label_11.setObjectName("label_11")
        self.remarks = QtWidgets.QTextEdit(self.groupSupplier)
        self.remarks.setGeometry(QtCore.QRect(20, 370, 561, 75))
        self.remarks.setObjectName("remarks")
        self.supplierName = QtWidgets.QComboBox(self.groupSupplier)
        self.supplierName.setGeometry(QtCore.QRect(70, 16, 211, 27))
        self.supplierName.setObjectName("supplierName")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.btnGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.btnGroup.setGeometry(QtCore.QRect(9, 510, 601, 51))
        self.btnGroup.setStyleSheet("border:1px solid #ccc; border-radius:2px;")
        self.btnGroup.setTitle("")
        self.btnGroup.setObjectName("btnGroup")
        self.btnSave = QtWidgets.QPushButton(self.btnGroup)
        self.btnSave.setGeometry(QtCore.QRect(468, 10, 81, 31))
        self.btnSave.setStyleSheet("color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 127);\n"
"background-color: rgb(0, 85, 0);\n"
"alternate-background-color: rgb(0, 170, 0);")
        self.btnSave.setObjectName("btnSave")
        self.btnClose = QtWidgets.QPushButton(self.btnGroup)
        self.btnClose.setGeometry(QtCore.QRect(50, 10, 81, 31))
        self.btnClose.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 0, 0);\n"
"alternate-background-color: rgb(255, 0, 127);")
        self.btnClose.setObjectName("btnClose")
        Supplier.setCentralWidget(self.centralWidget)

        self.retranslateUi(Supplier)
        self.btnClose.clicked.connect(Supplier.close)
        QtCore.QMetaObject.connectSlotsByName(Supplier)

    def retranslateUi(self, Supplier):
        _translate = QtCore.QCoreApplication.translate
        Supplier.setWindowTitle(_translate("Supplier", "Supplier"))
        self.label.setText(_translate("Supplier", "Name:"))
        self.label_2.setText(_translate("Supplier", "Contact:"))
        self.label_3.setText(_translate("Supplier", "City:"))
        self.label_4.setText(_translate("Supplier", "Region:"))
        self.label_5.setText(_translate("Supplier", "Fax:"))
        self.label_6.setText(_translate("Supplier", "Address:"))
        self.label_7.setText(_translate("Supplier", "Postal Address:"))
        self.label_8.setText(_translate("Supplier", "Registration Number:"))
        self.label_9.setText(_translate("Supplier", "Email:"))
        self.label_10.setText(_translate("Supplier", "Products in store:"))
        self.label_11.setText(_translate("Supplier", "Your remarks about this supplier:"))
        self.label_12.setText(_translate("Supplier", "New Supplier Information"))
        self.btnSave.setText(_translate("Supplier", "Save"))
        self.btnClose.setText(_translate("Supplier", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Supplier = QtWidgets.QMainWindow()
    ui = Ui_Supplier()
    ui.setupUi(Supplier)
    Supplier.show()
    sys.exit(app.exec_())

