# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logs.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Logs(object):
    def setupUi(self, Logs):
        Logs.setObjectName("Logs")
        Logs.resize(887, 563)
        Logs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Logs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupBox = QtWidgets.QGroupBox(Logs)
        self.groupBox.setGeometry(QtCore.QRect(610, 192, 131, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("border: 1px solid #ccc")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnReset = QtWidgets.QPushButton(self.groupBox)
        self.btnReset.setGeometry(QtCore.QRect(15, 20, 99, 27))
        self.btnReset.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnReset.setObjectName("btnReset")
        self.btnExportExcel = QtWidgets.QPushButton(self.groupBox)
        self.btnExportExcel.setGeometry(QtCore.QRect(15, 70, 99, 27))
        self.btnExportExcel.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.btnExportExcel.setObjectName("btnExportExcel")
        self.btnExportCSV = QtWidgets.QPushButton(self.groupBox)
        self.btnExportCSV.setGeometry(QtCore.QRect(15, 120, 99, 27))
        self.btnExportCSV.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnExportCSV.setObjectName("btnExportCSV")
        self.btnDeleteAll = QtWidgets.QPushButton(self.groupBox)
        self.btnDeleteAll.setGeometry(QtCore.QRect(15, 170, 99, 27))
        self.btnDeleteAll.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnDeleteAll.setObjectName("btnDeleteAll")
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setGeometry(QtCore.QRect(15, 220, 99, 27))
        self.btnCancel.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.btnCancel.setObjectName("btnCancel")
        self.label_2 = QtWidgets.QLabel(Logs)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 661, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 48, 70);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tableView = QtWidgets.QTableView(Logs)
        self.tableView.setGeometry(QtCore.QRect(80, 220, 511, 251))
        self.tableView.setObjectName("tableView")
        self.columnView_2 = QtWidgets.QColumnView(Logs)
        self.columnView_2.setGeometry(QtCore.QRect(80, 190, 131, 31))
        self.columnView_2.setStyleSheet("background-color: rgba(0, 85, 127, 200);")
        self.columnView_2.setObjectName("columnView_2")
        self.columnView_3 = QtWidgets.QColumnView(Logs)
        self.columnView_3.setGeometry(QtCore.QRect(211, 190, 131, 31))
        self.columnView_3.setStyleSheet("background-color: rgba(0, 85, 127, 200);")
        self.columnView_3.setObjectName("columnView_3")
        self.columnView_4 = QtWidgets.QColumnView(Logs)
        self.columnView_4.setGeometry(QtCore.QRect(341, 190, 251, 31))
        self.columnView_4.setStyleSheet("background-color: rgba(0, 85, 127, 200);")
        self.columnView_4.setObjectName("columnView_4")
        self.label = QtWidgets.QLabel(Logs)
        self.label.setGeometry(QtCore.QRect(110, 196, 68, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Logs)
        self.label_3.setGeometry(QtCore.QRect(260, 196, 68, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Logs)
        self.label_4.setGeometry(QtCore.QRect(420, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#fff")
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Logs)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 90, 661, 80))
        self.groupBox_2.setStyleSheet("border:1px solid #ccc;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 451, 61))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 30, 171, 51))
        self.groupBox_5.setStyleSheet("border:0;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_2.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.dateEdit_2.setStyleSheet("border:1px solid #999; border-radius:3px;")
        self.dateEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_2.setDate(QtCore.QDate(2017, 1, 1))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 68, 17))
        self.label_5.setStyleSheet("border:0;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(190, 10, 61, 20))
        self.label_6.setStyleSheet("border:0;")
        self.label_6.setObjectName("label_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(280, 50, 171, 31))
        self.groupBox_6.setStyleSheet("border:0;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_3.setGeometry(QtCore.QRect(190, 30, 161, 21))
        self.dateEdit_3.setStyleSheet("border:1px solid #999; border-radius:3px;")
        self.dateEdit_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit_3.setDate(QtCore.QDate(2017, 1, 1))
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(360, 20, 81, 31))
        self.pushButton.setStyleSheet("border-radius:3px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);padding-top:3px;padding-bottom:3px;")
        self.pushButton.setObjectName("pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(470, 10, 181, 61))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.label_7.setStyleSheet("border:0;")
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 161, 21))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Logs)
        QtCore.QMetaObject.connectSlotsByName(Logs)

    def retranslateUi(self, Logs):
        _translate = QtCore.QCoreApplication.translate
        Logs.setWindowTitle(_translate("Logs", "Activity Logs"))
        self.btnReset.setText(_translate("Logs", "Reset"))
        self.btnExportExcel.setText(_translate("Logs", "Export Excel"))
        self.btnExportCSV.setText(_translate("Logs", "Export CSV"))
        self.btnDeleteAll.setText(_translate("Logs", "Delete All"))
        self.btnCancel.setText(_translate("Logs", "Cancel"))
        self.label_2.setText(_translate("Logs", "Activity Logs"))
        self.label.setText(_translate("Logs", "User ID"))
        self.label_3.setText(_translate("Logs", "Date"))
        self.label_4.setText(_translate("Logs", "Operation"))
        self.label_5.setText(_translate("Logs", "From:"))
        self.label_6.setText(_translate("Logs", "To:"))
        self.pushButton.setText(_translate("Logs", "Get Data"))
        self.label_7.setText(_translate("Logs", "User ID:"))


def showLogs():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        Logs = QtWidgets.QFrame()
        ui = Ui_Logs()
        ui.setupUi(Logs)
        Logs.show()
        sys.exit(app.exec_())