# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wzcategories.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wzrdCategories(object):
    def setupUi(self, wzrdCategories):
        wzrdCategories.setObjectName("wzrdCategories")
        wzrdCategories.resize(883, 538)
        self.groupBox_2 = QtWidgets.QGroupBox(wzrdCategories)
        self.groupBox_2.setGeometry(QtCore.QRect(129, 370, 611, 61))
        self.groupBox_2.setStyleSheet("border:1px solid #ccc;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.showCategory = QtWidgets.QLineEdit(self.groupBox_2)
        self.showCategory.setGeometry(QtCore.QRect(120, 20, 381, 27))
        self.showCategory.setObjectName("showCategory")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:0;")
        self.label_2.setLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(wzrdCategories)
        self.groupBox.setGeometry(QtCore.QRect(609, 110, 131, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("border: 1px solid #ccc")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnNew = QtWidgets.QPushButton(self.groupBox)
        self.btnNew.setGeometry(QtCore.QRect(15, 10, 99, 27))
        self.btnNew.setObjectName("btnNew")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setGeometry(QtCore.QRect(15, 60, 99, 27))
        self.btnSave.setObjectName("btnSave")
        self.btnUpdate = QtWidgets.QPushButton(self.groupBox)
        self.btnUpdate.setGeometry(QtCore.QRect(15, 110, 99, 27))
        self.btnUpdate.setObjectName("btnUpdate")
        self.btnDelete = QtWidgets.QPushButton(self.groupBox)
        self.btnDelete.setGeometry(QtCore.QRect(15, 160, 99, 27))
        self.btnDelete.setObjectName("btnDelete")
        self.btnCancel = QtWidgets.QPushButton(self.groupBox)
        self.btnCancel.setGeometry(QtCore.QRect(15, 210, 99, 27))
        self.btnCancel.setObjectName("btnCancel")
        self.groupBox_3 = QtWidgets.QGroupBox(wzrdCategories)
        self.groupBox_3.setGeometry(QtCore.QRect(129, 20, 611, 80))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(330, 30, 261, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(280, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(wzrdCategories)
        self.tableWidget.setGeometry(QtCore.QRect(129, 108, 461, 251))
        self.tableWidget.setStyleSheet("border:2px solid #dcdcdc;")
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(wzrdCategories)
        self.label.setGeometry(QtCore.QRect(130, 110, 459, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 48, 70);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(wzrdCategories)
        QtCore.QMetaObject.connectSlotsByName(wzrdCategories)

    def retranslateUi(self, wzrdCategories):
        _translate = QtCore.QCoreApplication.translate
        wzrdCategories.setWindowTitle(_translate("wzrdCategories", "WizardPage"))
        self.label_2.setText(_translate("wzrdCategories", "Category"))
        self.btnNew.setText(_translate("wzrdCategories", "New"))
        self.btnSave.setText(_translate("wzrdCategories", "Save"))
        self.btnUpdate.setText(_translate("wzrdCategories", "Update"))
        self.btnDelete.setText(_translate("wzrdCategories", "Delete"))
        self.btnCancel.setText(_translate("wzrdCategories", "Cancel"))
        self.label_3.setText(_translate("wzrdCategories", "List of All Categories"))
        self.lineEdit.setPlaceholderText(_translate("wzrdCategories", "Filter"))
        self.label_4.setText(_translate("wzrdCategories", "Filter"))
        self.label.setText(_translate("wzrdCategories", "Categories"))


def showWizardCategories():
    if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        wzrdCategories = QtWidgets.QWizardPage()
        ui = Ui_wzrdCategories()
        ui.setupUi(wzrdCategories)
        wzrdCategories.show()
        sys.exit(app.exec_())
