# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'users.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import sql

class Ui_Users(object):
    def setupUi(self, Users):
        Users.setObjectName("Users")
        Users.resize(771, 570)
        Users.setMaximumSize(QtCore.QSize(771, 570))
        self.widgetUsers = QtWidgets.QTableView(Users)
        self.widgetUsers.setGeometry(QtCore.QRect(20, 130, 731, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.widgetUsers.sizePolicy().hasHeightForWidth())
        self.widgetUsers.setSizePolicy(sizePolicy)
        self.widgetUsers.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widgetUsers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgetUsers.setLineWidth(1)
        self.widgetUsers.setMidLineWidth(0)
        self.widgetUsers.setAlternatingRowColors(True)
        self.widgetUsers.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetUsers.setIconSize(QtCore.QSize(0, 0))
        self.widgetUsers.setShowGrid(False)
        self.widgetUsers.setGridStyle(QtCore.Qt.CustomDashLine)
        self.widgetUsers.setSortingEnabled(True)
        self.widgetUsers.setObjectName("widgetUsers")
        self.groupBox_3 = QtWidgets.QGroupBox(Users)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 60, 411, 61))
        self.groupBox_3.setStyleSheet("background-color: rgb(255,255,255);\n"
"border:1px solid #999;\n"
"border-radius: 4px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnReset = QtWidgets.QPushButton(self.groupBox_3)
        self.btnReset.setGeometry(QtCore.QRect(10, 10, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btnReset.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnReset.setFont(font)
        self.btnReset.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/Reset2_32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReset.setIcon(icon)
        self.btnReset.setIconSize(QtCore.QSize(25, 25))
        self.btnReset.setAutoDefault(False)
        self.btnReset.setObjectName("btnReset")
        self.btnExport = QtWidgets.QPushButton(self.groupBox_3)
        self.btnExport.setGeometry(QtCore.QRect(120, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnExport.setFont(font)
        self.btnExport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnExport.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("src/Excel-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExport.setIcon(icon1)
        self.btnExport.setIconSize(QtCore.QSize(25, 25))
        self.btnExport.setAutoDefault(False)
        self.btnExport.setObjectName("btnExport")
        self.btnRemove = QtWidgets.QPushButton(self.groupBox_3)
        self.btnRemove.setGeometry(QtCore.QRect(250, 9, 71, 41))
        self.btnRemove.setObjectName("btnRemove")
        self.btnEddit = QtWidgets.QPushButton(self.groupBox_3)
        self.btnEddit.setGeometry(QtCore.QRect(330, 10, 71, 41))
        self.btnEddit.setObjectName("btnEddit")
        self.groupBox_2 = QtWidgets.QGroupBox(Users)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 60, 311, 61))
        self.groupBox_2.setStyleSheet("background-color: rgb(255,255,255);\n"
"border:1px solid #999;\n"
"border-radius: 4px;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.search_users = QtWidgets.QLineEdit(self.groupBox_2)
        self.search_users.setGeometry(QtCore.QRect(10, 27, 221, 25))
        self.search_users.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.search_users.setObjectName("search_users")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 4, 191, 21))
        self.label_7.setStyleSheet("border:0;")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(236, 26, 61, 27))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Users)
        self.label.setGeometry(QtCore.QRect(0, 0, 771, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnClose = QtWidgets.QPushButton(Users)
        self.btnClose.setGeometry(QtCore.QRect(653, 520, 99, 41))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(Users)
        self.btnClose.clicked.connect(Users.close)
        self.btnReset.clicked.connect(self.widgetUsers.reset)
        QtCore.QMetaObject.connectSlotsByName(Users)

    def retranslateUi(self, Users):
        _translate = QtCore.QCoreApplication.translate
        Users.setWindowTitle(_translate("Users", "All users"))
        self.btnReset.setText(_translate("Users", "Reset"))
        self.btnExport.setText(_translate("Users", "Export excel"))
        self.btnRemove.setText(_translate("Users", "Remove"))
        self.btnEddit.setText(_translate("Users", "Edit"))
        self.label_7.setText(_translate("Users", "Search by products name:"))
        self.pushButton.setText(_translate("Users", "Search"))
        self.label.setText(_translate("Users", "All Store Staffs"))
        self.btnClose.setText(_translate("Users", "Close"))


    def checkUser(self):
        sql.connectDB()
        model = QtSql.QSqlTableModel()
        model.setTable("users")
        model.select()
        model.setEditStrategy(QtSql.QSqlTableModel.OnManualSubmit)
        model.setHeaderData(0, QtCore.Qt.Horizontal, "ID")
        model.setHeaderData(1, QtCore.Qt.Horizontal, "Full Name")
        model.setHeaderData(2, QtCore.Qt.Horizontal, "Password")
        model.setHeaderData(4, QtCore.Qt.Horizontal, "Email")
        model.setHeaderData(5, QtCore.Qt.Horizontal, "Phone")
        model.setHeaderData(3, QtCore.Qt.Horizontal, "Username")
        model.setHeaderData(6, QtCore.Qt.Horizontal, "Type")
        model.setHeaderData(7, QtCore.Qt.Horizontal, "Status")
        self.widgetUsers.setModel(model)
        self.widgetUsers.setColumnHidden(0, True)
        self.widgetUsers.setColumnHidden(2, True)
        self.widgetUsers.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.widgetUsers.show()
